# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6f4c27d0c18aa44c148d234ba87b58bbaf656c3de9bc570c4cbe674a6772b5051b77a850dad89a6afed94d19a2f967bdb6ebdcccd47a4c701592535420c0376

test:
  secret_key_base: abb4e098a48c569bd3287747bd2e80b0f27ae42dbc642058da06cb64739fd100aa5a752bc7038ae863f46445545ae23713dc21abe91f5ab0382f75878ac37549

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
